name: Deploy (docker compose)

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Decide environment
        id: env
        run: |
          run: |
          BRANCH='${{ github.event.client_payload.branch }}'
          if [ "$BRANCH" = "main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "branch=main" >> $GITHUB_OUTPUT
          else
            echo "environment=test" >> $GITHUB_OUTPUT
            echo "branch=develop" >> $GITHUB_OUTPUT
          fi

      - name: Deploy via SSH
        environment: ${{ steps.env.outputs.environment }}
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch --all
            git checkout ${{ steps.env.outputs.branch }}
            git pull origin ${{ steps.env.outputs.branch }}
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
